server:
  port: 8084 # Port on which the application will run

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adminmicroservice_db
    username: root
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
